### ISSUE TITLE
Could you share the paper?

### ISSUE THREAD

**Issue by cvengneer** [Liubinggunzu/VLAD-VSA#1]
Hi, big thanks for sharing the code.

Couldn't find full paper in pdf. Can you share it?

Thank you!

**Comment by Liubinggunzu** [comment]
Sorry for the inconvenience. You can download the VLAD-VSA paper here([Googledrive,](https://drive.google.com/file/d/1hcH2AHwInelY4nfJdWonN6cDdAIE4TlG) [BaiduDrive](https://pan.baidu.com/s/1TiR0KBRgt4lRr5ep8YzC7g), Fetch Code: st5g), and we will upload it to Arxiv soon!

**Comment by cvengneer** [comment]
@Liubinggunzu Thank you very much! :+1:
