### ISSUE TITLE
请问为什么netvlad层的卷积参数初始化方式和原始netvlad定义不一样？

### ISSUE THREAD

**Issue by sherlockers** [Liubinggunzu/VLAD-VSA#3]

**Comment by Liubinggunzu** [comment]
nn.init.orthogonal_ get better results than other initialization. 
Another difference from netvlad is that only self.conv.weight is used for assignment and residual calculation, while the self.centroid  is not.  This comply with original VLAD that same visual words are used for assignment and residual calculation

**Comment by sherlockers** [comment]
非常感谢您的回答
