### ISSUE TITLE
请问vocabulary adaptation的loss为什么看起来与论文中不同？

### ISSUE THREAD

**Issue by shuimushan** [Liubinggunzu/VLAD-VSA#6]
非常感谢您分享您的工作，我想将您的思想运用到另外的领域中，由于电脑内存有限没能下载相关数据集运行代码，在阅读代码时发现两个vocabulary adaptation loss似乎与论文中有些许不同，希望您能解答我的困惑。
在论文中L<sub>intra</sub>是通过真假脸的特征相减得到的，而代码中对应的adap_loss_1看起来是相加；论文中L<sub>c_adapt</sub>看起来并没有数字1，代码中有加1。请问这些改动是与数据集相关的吗？

**Comment by Liubinggunzu** [comment]
代码是这样写的
```python
adap_loss_1 = 1 - torch.sum((wnorm * F.normalize((assign_sum_real + assign_sum_fake), p=2, dim=1)), -1)
adap_loss_2 = 1 + torch.sum(F.normalize((F.normalize(assign_sum_real, p=2, dim=1) - wnorm), p=2, dim=1) *
                                        F.normalize((F.normalize(assign_sum_fake, p=2, dim=1) - wnorm), p=2, dim=1), -1)
```
其中adap_loss_1 是Lc_adapt， adap_loss_2 是Lintra
- 求Lc_adapts的时候，要得到cluster center和feature center，然后求相似度作为loss（1减相似度）。assign_sum_real 是每个cluster内的real特征，assign_sum_fake是fake特征，加起来就是feature center， wnorm是cluster center。所以adap_loss_1 就求了两者的相似度和1比较，作为loss
-  求L intra时候，把cluster内的real特征与wnorm的残差（-wnorm）和fake 特征与wnorm的残差求相似度（论文中有个示意图），理想情况下相似度为-1，所以要1+，防止loss是负的

**Comment by shuimushan** [comment]
感谢您的解答！
